# Generated by Django 4.1.2 on 2022-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenterName',
            field=models.TextField(null=True),
        ),
    ]
