# Generated by Django 4.1.2 on 2022-10-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_comment_commentername'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='datePublished',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='comment',
            name='datePublished',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
    ]
